---
- hosts: all
  become: true
  tasks:
    - name: Get Docker container info
      shell: /opt/ansible/docker_ps.sh
      register: docker_ps_output

    - name: Check container status
      debug:
        msg: "{{ item.split('|')[0] }} is {{ item.split('|')[1] }}"
      loop: "{{ docker_ps_output.stdout_lines }}"
      loop_control:
        label: "Container: {{ item.split('|')[0] }}"

    - name: Start stopped containers
      docker_container:
        name: "{{ item.split('|')[0] }}"
        state: started
      loop: "{{ docker_ps_output.stdout_lines }}"
      when: "'Exited' in item.split('|')[1]"
      loop_control:
        label: "Container: {{ item.split('|')[0] }}"
