---
- hosts: all
  become: true  
  tasks:
    - name: Get Docker container info
      command: docker ps -a --format "{{.Names}}|{{.Status}}"
      register: docker_ps_output

    - name: Parse Docker container info
      set_fact:
        containers_info: "{{ docker_ps_output.stdout_lines | list }}"

    - name: Check container health
      debug:
        msg: "{{ item.split('|')[0] }} is {{ item.split('|')[1] }}"
      loop: "{{ containers_info }}"
      when: 
        - "not ('Up' in item.split('|')[1] or 'healthy' in item.split('|')[1])"

    - name: Start stopped containers
      docker_container:
        name: "{{ item.split('|')[0] }}"
        state: started
      loop: "{{ containers_info }}"
      when: "'Exited' in item.split('|')[1]"
