---
- hosts: all
  become: true  
  tasks:
    - name: Check Container Status  
      block:
        - name: Check each container status
          include_tasks: DockerStart.yml
          loop: "{{ ansible_facts.docker_container_info }}"
          loop_control:
            loop_var: item
