---
- hosts: all
  become: true  
  tasks:
    - name: Get Docker container info
      command: docker ps -a --format '{{json .}}'
      register: docker_ps_output

    - name: Parse Docker container info
      set_fact:
        containers_info: "{{ docker_ps_output.stdout | from_json }}"

    - name: Check container health
      debug:
        msg: "{{ item.Names }} is {{ item.Status }}"
      loop: "{{ containers_info }}"
      when: 
        - "not ('Up' in item.Status or 'healthy' in item.Status)"

    - name: Start stopped containers
      docker_container:
        name: "{{ item.Names }}"
        state: started
      loop: "{{ containers_info }}"
      when: "'Exited' in item.Status"
