---
- hosts: all
  become: true  
  tasks:
    - name: Gathering Docker Facts
      docker_container_info:
        register: containers

    - name: Check Container Status  
      block:
        - name: Check each container status
          include_tasks: check_container_status.yml
          loop: "{{ containers.results }}"
          loop_control:
            loop_var: item
