---
- hosts: all
  become: true
  tasks:
    - name: Gathering Docker Facts
      docker_container_info:
        register: containers

    - name: Check Container Status  # Loop outside the block
      loop: "{{ containers.results }}"
      when: item.state == "stopped"
      # Block with tasks to start container and handle errors (optional)

