---
- hosts: all
  become: true
  tasks:
    - name: update apt packages on remote hosts
      apt:
        upgrade: yes
        update_cache: yes
    - name: update apt packages on localhost
      local_action:
        module: apt
        upgrade: yes
        update_cache: yes
      vars:
        ansible_user: ansible
